default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chermeals_development
  username: postgres
  password: password
  host: localhost

test:
  <<: *default
  database: chermeals_test

production:
  <<: *default
  database: chermeals_production
  username: chermeals
  password: <%= ENV['CHERMEALS_DATABASE_PASSWORD'] %>
